### ISSUE TITLE
Help complete Q4OS and TDE Icons for Papirus

### ISSUE THREAD

**Issue by maxtron95** [jaerrib/waterleaf-icon-theme#10]
@q4osteam @jaerrib I am a member of the Papirus Development Team.
I wanted to know all of the icons for Q4OS and TDE that you have already done and ones that you haven't themed yet including TDE applications and Q4OS applications. This is so I can complete an issue PapirusDevelopmentTeam/papirus-icon-theme#1818 to have full compatibility with our icon theme and to help you complete your theme with the Papirus icons I create.

**Comment by jaerrib** [comment]
@creepertron95 Thanks for the offer of assistance. The changes I've made include original icons and symlinks to existing ones. There was also a substantial amount of work done for the theme in its pre-Waterleaf existence as Paper-Q4OS. While there's some inconsistency in style that needs to be addressed over time, I can try to put together a list to help you out in the meantime. Are you looking for a more general list or one containing specifics, such as 16x16/apps/tdepowersave.svg?

**Comment by maxtron95** [comment]
@jaerrib Could a zipped file containing the original icons and their names and a specific list be sufficient for all TDE and Q4OS applications that is in Q4OS and its repositories?

**Comment by jaerrib** [comment]
@creepertron95 [This zip file](https://github.com/jaerrib/waterleaf-icon-theme/files/3776052/waterleaf.zip) should contain the various changes I've made (original work, symlinks, etc.) Development started out with different individuals in a different repo and wasn't exactly organized so I couldn't just look at created/modified dates. I ended up browsing forum posts and previous commits to figure out what I had done. There are also some updates that happened when I rebased on the work the Q4OS team did for the Centaurus release; those icons/symlinks may or may not be TDE specific. Sorry for the chaotic nature of all this; it's been a bit of an evolution that happened organically rather than something that was planned out.

_Edit: I forgot you also asked for [a list](https://github.com/jaerrib/waterleaf-icon-theme/files/3776074/icon_list.txt). Aside from direction from the Q4OS team, I used what existed in the crystalsvg theme as a guide for creating new icons as well._

**Comment by maxtron95** [comment]
@jaerrib There are extra programs that are part of the Trinity Desktop Environment. 
Do you think that we could identify the icon names of them in Q4OS? 
https://www.trinitydesktop.org/applications.php

**Comment by jaerrib** [comment]
Most of the applications have -trinity appended to the package name. However, the icons don't necessarily follow that. For example, there's no difference between konqueror and konqueror-trinity as far as the icons go. There are also various UI icons, such as scheme_advanced_powersave. I'll work on putting together an application list first since that's more straightforward. The UI part will take a bit more time; I haven't quite figured all of those out just yet.

**Comment by maxtron95** [comment]
Do you think the original icons for the applications can be found and packaged in a zip file for reference?

**Comment by jaerrib** [comment]
Sorry for the delay. The icons in these zip files ([crystalsvg.zip](https://github.com/jaerrib/waterleaf-icon-theme/files/3829198/crystalsvg.zip) [hicolor.zip](https://github.com/jaerrib/waterleaf-icon-theme/files/3829199/hicolor.zip)) cover most of the applications, but there are some missing (which is why filling in the gaps has been troublesome.)

**Comment by maxtron95** [comment]
@jaerrib I found where TDE and its applications hides its icons. They are located at /opt/trinity/share/icons. You have to install the other TDE application packages for their icons to appear but I found them.

**Comment by jaerrib** [comment]
Thanks for updating me on your progress. (Sorry for the delayed response due to work, holidays and whatnot.) As you create any missing icons, would you like to add them to the Waterleaf repo? Right now, I'm just borrowing icons from Papirus here and there when I'm not adding symlinks or making my own icons. I'm fine with that approach as well.

**Comment by jaerrib** [comment]
Unless you want to add the icons you're creating to the Waterleaf repo, I'm going to close this bug report as it is aimed more at updating the Papirus icon theme than this one.

**Comment by maxtron95** [comment]
@jaerrib It is fine if you close the issue but, I have a question. Could I upload the icons I created for Papirus as their original form or should I modify them?

**Comment by jaerrib** [comment]
You're welcome to upload them in their original forms. The color palette might need tweaked slightly but sometimes the Papirus stuff fits in just fine.
